import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function HtmlLayout({ children }) {
  console.log('d256 HtmlLayout:')
  return (
    <html lang="en" className="h-full bg-white">
      <body className={"h-full"}>
        {children}
      </body>
    </html>
  )
}


