import {
  BellIcon,
  BriefcaseIcon,
  ChatBubbleBottomCenterIcon, CursorArrowRaysIcon, GlobeAltIcon,
  GlobeEuropeAfricaIcon,
  HomeIcon, HomeModernIcon,
  TrophyIcon,
  UsersIcon
} from "@heroicons/react/24/outline";

export const articleList = [
  {
    id: 'WQKTAMH72MOQWQCUFZMH2SR6BE',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: '3ZWH3N6T3ISVW6XOT422FT224Y',
      additional_properties: [Object],
      address: {},
      auth: [Object],
      caption: 'Today is the first day Australians can travel to New Zealand without being quarantined in MIQ for 14 days. Photo / Michael Craig',
      created_date: '2021-04-19T00:49:21Z',
      height: 1280,
      last_updated_date: '2021-04-19T00:49:21Z',
      licensable: false,
      owner: [Object],
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/3ZWH3N6T3ISVW6XOT422FT224Y.jpg',
      version: '0.10.9',
      width: 1920,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Two new Covid cases in MIQ as we burst the transtasman bubble',
    displayDate: '2023-07-26T05:09:57.192Z',
    publishDate: '2023-07-26T05:09:57.192Z',
    isUpdated: false,
    description: 'The Ministry of Health is due to release the latest Covid-19 case figures.',
    readTime: '4 minutes to read',
    websiteUrl: '/whanganui-chronicle/news/covid-19-coronavirus-two-new-virus-cases-in-miq-none-in-community-on-first-day-of-transtasman-bubble/WQKTAMH72MOQWQCUFZMH2SR6BE/',
    linkTarget: '_self',
    source: {
      edit_url: 'https://dev-zen.devlbcf.apnnz.co.nz/v2/index.cfm?page=article&objectid=12436642',
      name: "Woman's Day",
      source_id: '12436642',
      source_type: 'other',
      system: 'Zen'
    },
    sections: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    website: 'whanganui-chronicle',
    tags: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    authors: [],
    hasArticlePromoVideo: '6249337523001',
    nzhVideo: {},
    accentColor: 'section-whanganui-chronicle',
    sectionLabel: 'Whanganui Chronicle',
    sectionLabelLink: '/whanganui-chronicle/news/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: 'FCJ4PKXKNVBO5DR3TOCV5S5IKQ',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'HQSYVFPT3RHRXWB7DI6XB5BHLQ',
      additional_properties: [Object],
      address: {},
      auth: [Object],
      caption: '',
      created_date: '2023-04-18T00:23:01Z',
      height: 1080,
      last_updated_date: '2023-04-18T00:23:01Z',
      licensable: false,
      owner: [Object],
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/HQSYVFPT3RHRXWB7DI6XB5BHLQ.jpg',
      version: '0.10.9',
      width: 1920,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'iHeart Pname tracking test article',
    displayDate: '2023-04-18T03:45:00.486Z',
    publishDate: '2023-05-30T23:45:02.924Z',
    isUpdated: false,
    description: 'iHeart Pname tracking test article',
    readTime: 'Quick Read',
    websiteUrl: '/whanganui-chronicle/news/iheart-pname-tracking-test-article/FCJ4PKXKNVBO5DR3TOCV5S5IKQ/',
    linkTarget: '_self',
    source: { name: 'NZ Herald', source_type: 'staff', system: 'composer' },
    sections: [ [Object], [Object], [Object] ],
    website: 'whanganui-chronicle',
    authors: [],
    hasArticlePromoVideo: false,
    nzhVideo: {},
    accentColor: 'section-whanganui-chronicle',
    sectionLabel: 'Whanganui Chronicle',
    sectionLabelLink: '/whanganui-chronicle/news/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: 'UENHGEOKHJCLHBFF3E5K3GKBSU',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'LZWFYJ2Z526Z75JNL3PJKBTXRA',
      additional_properties: [Object],
      auth: [Object],
      caption: 'Political commentator Kerry-Anne Walsh at home in Canberra, Australia. Photo / Gary Ramage',
      created_date: '2022-11-08T04:59:57Z',
      height: 1280,
      last_updated_date: '2022-11-09T22:04:27Z',
      licensable: false,
      owner: [Object],
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/LZWFYJ2Z526Z75JNL3PJKBTXRA.jpg',
      version: '0.10.9',
      width: 1920,
      sets: [Object]
    },
    isPremium: true,
    displayComments: false,
    headline: 'Misogyny and political power plays: Why Canberra commentator Kerry-Anne Walsh walked away',
    displayDate: '2023-04-16T23:17:58.764Z',
    publishDate: '2023-04-16T23:17:58.764Z',
    isUpdated: false,
    description: '"Most of the male journalists I worked with were terrific, but some were absolute f***s."',
    readTime: 'Quick Read',
    websiteUrl: '/whanganui-chronicle/property/very-bad-article-pw-break-tung-test/UENHGEOKHJCLHBFF3E5K3GKBSU/',
    linkTarget: '_self',
    source: { name: 'nzme', source_type: 'staff', system: 'composer' },
    sections: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    website: 'whanganui-chronicle',
    tags: [ [Object], [Object], [Object] ],
    authors: [ [Object] ],
    hasArticlePromoVideo: false,
    nzhVideo: {},
    accentColor: 'section-property',
    sectionLabel: 'Property',
    sectionLabelLink: '/whanganui-chronicle/property/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'big-read'
  },
  {
    id: 'AJ6CZBZGCZH6NHXW5MPL4SB3GA',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'WK4EQYE5IK3CIPAM3OPIC4YZHY',
      additional_properties: [Object],
      address: [Object],
      auth: [Object],
      caption: 'Photo / Getty Images',
      copyright: '-',
      created_date: '2022-11-19T21:00:04Z',
      distributor: [Object],
      height: 1243,
      last_updated_date: '2022-11-19T23:00:50Z',
      licensable: false,
      owner: [Object],
      slug: 'WAC0559015056',
      source: [Object],
      subtitle: 'CRICKET BALL AND BAILS WITH COPY SPACE',
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/WK4EQYE5IK3CIPAM3OPIC4YZHY.jpg',
      version: '0.10.9',
      width: 1920,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Video Play/Pause Test - Kiran',
    displayDate: '2023-02-27T20:44:15.873Z',
    publishDate: '2023-02-27T20:44:15.873Z',
    isUpdated: false,
    description: 'Kiran Testings',
    readTime: 'Quick Read',
    websiteUrl: '/whanganui-chronicle/business/video-playpause-test-kiran/AJ6CZBZGCZH6NHXW5MPL4SB3GA/',
    linkTarget: '_self',
    source: { name: 'NZ Herald', source_type: 'staff', system: 'composer' },
    sections: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    website: 'whanganui-chronicle',
    authors: [],
    hasArticlePromoVideo: false,
    nzhVideo: { id: 'SFSV7F34ESQOH3NXXLYIGQOGTI', website: 'nzh' },
    accentColor: 'section-business',
    sectionLabel: 'Business',
    sectionLabelLink: '/whanganui-chronicle/business/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: '64IST52UMHPOLSFSUGCC24BQZM',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'EUJ2AJXLNCAFDHYAA6TOAXBTXM',
      additional_properties: [Object],
      auth: [Object],
      caption: 'Flowers. Photo / Stock',
      created_date: '2021-11-25T20:11:12Z',
      height: 1280,
      last_updated_date: '2021-11-25T20:18:32Z',
      licensable: false,
      owner: [Object],
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/EUJ2AJXLNCAFDHYAA6TOAXBTXM.jpg',
      version: '0.10.9',
      width: 1920,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Death notices',
    displayDate: '2023-02-27T19:59:00Z',
    publishDate: '2023-03-24T00:01:55.683Z',
    isUpdated: false,
    description: 'Search for, or place a death notice in-paper and online.',
    readTime: 'Quick Read',
    websiteUrl: '/whanganui-chronicle/news/death-notices/64IST52UMHPOLSFSUGCC24BQZM/',
    linkTarget: '_self',
    source: {
      edit_url: 'https://zen.nzherald.co.nz/v2/index.cfm?page=article&objectid=12488791',
      name: 'nzme',
      source_id: '12488791',
      source_type: 'staff',
      system: 'Zen'
    },
    sections: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    website: 'whanganui-chronicle',
    authors: [],
    hasArticlePromoVideo: false,
    nzhVideo: {},
    accentColor: 'section-whanganui-chronicle',
    sectionLabel: 'Whanganui Chronicle',
    sectionLabelLink: '/whanganui-chronicle/news/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: 'GSDYL4WTWVEKNK2UBMQX4XW4OQ',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'AVCVUYDCKCL423I5MYYFZQBAZQ',
      additional_properties: [Object],
      caption: 'Indian batsman Virat Kohli in action against New Zealand Black Caps. Photo/Brett Phibbs',
      created_date: '2020-09-03T22:18:22Z',
      height: 1167,
      last_updated_date: '2020-09-03T22:18:22Z',
      licensable: false,
      owner: [Object],
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/AVCVUYDCKCL423I5MYYFZQBAZQ.jpg',
      version: '0.10.3',
      width: 1920,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Kiran Testing - Most Popular section in RH rail - NZH',
    displayDate: '2023-01-19T22:27:02.689Z',
    publishDate: '2023-01-19T22:27:02.689Z',
    isUpdated: false,
    description: 'Testing Most Popular section in RH rail',
    readTime: 'Quick Read',
    websiteUrl: '/whanganui-chronicle/business/kiran-testing-most-popular-section-in-rh-rail-nzh/GSDYL4WTWVEKNK2UBMQX4XW4OQ/',
    linkTarget: '_self',
    source: { name: 'NZ Herald', source_type: 'staff', system: 'composer' },
    sections: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ],
    website: 'whanganui-chronicle',
    authors: [],
    hasArticlePromoVideo: false,
    nzhVideo: {},
    accentColor: 'section-business',
    sectionLabel: 'Business',
    sectionLabelLink: '/whanganui-chronicle/business/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: '4MXU24CITFBZJKWY24OKOCUNYQ',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'GZA6X2YB6HRE6KK5PKITEZIBHE',
      additional_properties: [Object],
      address: {},
      caption: 'From politics to romance, this round-up will have you set for summer. Photo / Getty Images',
      created_date: '2022-11-10T13:04:01Z',
      distributor: [Object],
      height: 1120,
      last_updated_date: '2022-11-16T07:48:08Z',
      licensable: false,
      owner: [Object],
      slug: '611464497',
      source: [Object],
      subtitle: 'Young Woman With Dog Reading Book While Relaxing On Beach',
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/GZA6X2YB6HRE6KK5PKITEZIBHE.jpg',
      version: '0.10.3',
      width: 1500,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'This pet story is something you have to read',
    displayDate: '2022-12-15T22:55:00Z',
    publishDate: '2023-01-09T03:04:11.067Z',
    isUpdated: false,
    description: "This is about the story - isn't it great.",
    readTime: '3 minutes to read',
    websiteUrl: '/whanganui-chronicle/business/this-is-toni-easts-story-about-pets/4MXU24CITFBZJKWY24OKOCUNYQ/',
    linkTarget: '_self',
    source: {
      name: 'Financial Times',
      source_type: 'other',
      system: 'composer'
    },
    sections: [ [Object], [Object], [Object], [Object], [Object] ],
    website: 'whanganui-chronicle',
    tags: [ [Object], [Object], [Object], [Object] ],
    authors: [ [Object], [Object] ],
    hasArticlePromoVideo: false,
    nzhVideo: { id: 'OICUQGZEOVDG7OUBOXQZYW3ONQ', website: 'nzh' },
    accentColor: 'section-business',
    sectionLabel: 'Business',
    sectionLabelLink: '/whanganui-chronicle/business/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: 'IIB5FG6FBEU66NWAK4FDA4UVPE',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'YR3U6ZV5CYWJCVHNRDW2LSC5XM',
      additional_properties: [Object],
      address: [Object],
      caption: 'The increasing prices of fruit and seasonal vegetables is just one of the challenges facing many whānau. Photo / Sylvie Whinray',
      copyright: '-',
      created_date: '2022-03-15T05:54:47Z',
      height: 1280,
      last_updated_date: '2022-03-15T05:54:47Z',
      licensable: false,
      owner: [Object],
      slug: 'NZH0558968891',
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/YR3U6ZV5CYWJCVHNRDW2LSC5XM.jpg',
      version: '0.10.3',
      width: 1920,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Debbie Ngarewa-Packer: Fixing cost of living crisis needs new thinking',
    displayDate: '2022-12-12T06:25:52.887Z',
    publishDate: '2022-12-12T06:25:52.887Z',
    isUpdated: false,
    description: 'Taking GST off fresh produce one way to help whanau cope with surging prices.',
    readTime: '4 minutes to read',
    websiteUrl: '/whanganui-chronicle/news/debbie-ngarewa-packer-government-has-power-to-address-cost-of-living-crisis-today/IIB5FG6FBEU66NWAK4FDA4UVPE/',
    linkTarget: '_self',
    source: {
      edit_url: 'https://zen.nzherald.co.nz/v2/index.cfm?page=article&objectid=12511148',
      name: 'nzme',
      source_id: '12511148',
      source_type: 'staff',
      system: 'Zen'
    },
    sections: [ [Object], [Object], [Object], [Object] ],
    website: 'whanganui-chronicle',
    tags: [ [Object], [Object], [Object] ],
    authors: [],
    hasArticlePromoVideo: '6300321731001',
    nzhVideo: {},
    accentColor: 'section-whanganui-chronicle',
    sectionLabel: 'Whanganui Chronicle',
    sectionLabelLink: '/whanganui-chronicle/news/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: 'ZGVPJP7JSVBWZHRCLJA63WEG3Y',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'K6NLTLCOGPKWPPFXLQU655SBGY',
      additional_properties: [Object],
      caption: "Explore Hawke's Bay's coastline, and take in the stunning scenery of Waipatiki Beach. Picture / Supplied. ",
      created_date: '2022-11-09T01:45:47Z',
      height: 1000,
      last_updated_date: '2022-11-09T01:45:48Z',
      licensable: false,
      owner: [Object],
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/K6NLTLCOGPKWPPFXLQU655SBGY.jpg',
      version: '0.10.3',
      width: 1500,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Testing Mrec for WC',
    displayDate: '2022-12-05T22:03:04.894Z',
    publishDate: '2022-12-22T22:45:51.307Z',
    isUpdated: false,
    description: 'Own her miss cold last. It so numerous if he outlived disposal.',
    readTime: 'Quick Read',
    websiteUrl: '/whanganui-chronicle/news/testing-mrec-for-wc/ZGVPJP7JSVBWZHRCLJA63WEG3Y/',
    linkTarget: '_self',
    source: {
      name: 'Whanganui Midweek',
      source_type: 'staff',
      system: 'composer'
    },
    sections: [ [Object] ],
    website: 'whanganui-chronicle',
    tags: [ [Object] ],
    authors: [],
    hasArticlePromoVideo: false,
    nzhVideo: {},
    accentColor: 'section-whanganui-chronicle',
    sectionLabel: 'Whanganui Chronicle',
    sectionLabelLink: '/whanganui-chronicle/news/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: 'OE6KRGPJ5VETLKCU3UM55T6OIE',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'MSVQ4YCR3HAWNNGBOJDVSPLTDA',
      additional_properties: [Object],
      address: {},
      caption: '',
      created_date: '2022-12-05T18:24:37Z',
      height: 1080,
      last_updated_date: '2022-12-05T18:24:37Z',
      licensable: false,
      owner: [Object],
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/MSVQ4YCR3HAWNNGBOJDVSPLTDA.jpg',
      version: '0.10.3',
      width: 1920,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Testing news and regional template',
    displayDate: '2022-12-05T21:48:41.763Z',
    publishDate: '2023-01-09T03:16:02.024Z',
    isUpdated: false,
    description: 'Kindness to he horrible reserved ye.',
    readTime: 'Quick Read',
    websiteUrl: '/whanganui-chronicle/news/testing-news-and-regional-template/OE6KRGPJ5VETLKCU3UM55T6OIE/',
    linkTarget: '_self',
    source: { name: 'NZ Herald', source_type: 'staff', system: 'composer' },
    sections: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    website: 'whanganui-chronicle',
    authors: [],
    hasArticlePromoVideo: false,
    nzhVideo: {},
    accentColor: 'section-whanganui-chronicle',
    sectionLabel: 'Whanganui Chronicle',
    sectionLabelLink: '/whanganui-chronicle/news/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: 'LEENMIJWCVCLNHHTBETSPARBOY',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'EP3JXE6T4VEL5DZB7CXJMOYLG4',
      additional_properties: [Object],
      address: [Object],
      caption: '11 November 2022 Whanganui Chronicle Photo by Paul Brooks\rWGP 16Nov22 - Trudi Deane at her farewell function last week. Photo / Paul Brooks\r',
      copyright: 'Whanganui Chronicle',
      created_date: '2022-11-15T20:56:38Z',
      credits: [Object],
      distributor: [Object],
      height: 2476,
      image_type: 'photograph',
      last_updated_date: '2022-11-15T20:56:38Z',
      licensable: false,
      owner: [Object],
      slug: 'WAC0559269639',
      source: [Object],
      taxonomy: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/EP3JXE6T4VEL5DZB7CXJMOYLG4.JPG',
      version: '0.10.3',
      width: 2900,
      syndication: {},
      creditIPTC: 'Whanganui Chronicle',
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Hunterville of old in new book',
    displayDate: '2022-11-22T16:00:00Z',
    publishDate: '2022-11-22T16:00:00.297Z',
    isUpdated: false,
    description: 'New book grew from family stories',
    readTime: '2 minutes to read',
    websiteUrl: '/whanganui-chronicle/news/hunterville-book-portrays-life-as-we-knew-it/LEENMIJWCVCLNHHTBETSPARBOY/',
    linkTarget: '_self',
    source: {
      name: 'Whanganui Midweek',
      source_type: 'staff',
      system: 'composer'
    },
    sections: [ [Object] ],
    website: 'whanganui-chronicle',
    tags: [ [Object] ],
    authors: [ [Object] ],
    hasArticlePromoVideo: false,
    nzhVideo: {},
    accentColor: 'section-whanganui-chronicle',
    sectionLabel: 'Whanganui Chronicle',
    sectionLabelLink: '/whanganui-chronicle/news/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: false,
    subtype: 'news'
  },
  {
    id: 'CCU5I6FKOTN52JCV3KZHNJQQNY',
    contentType: 'story',
    showMeta: true,
    image: {
      _id: 'SZOYWQC2EZJ4MHMQZH7N66IYUE',
      additional_properties: [Object],
      auth: [Object],
      caption: 'Liberty Bracegirdle, owner of Recycle the Label, used her Amplify grant to take her business online. Photo / Supplied. ',
      created_date: '2022-11-21T00:34:09Z',
      height: 1280,
      last_updated_date: '2022-11-21T00:46:07Z',
      licensable: false,
      owner: [Object],
      source: [Object],
      type: 'image',
      url: 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/sandbox.nzme/SZOYWQC2EZJ4MHMQZH7N66IYUE.jpg',
      version: '0.10.9',
      width: 1920,
      sets: [Object]
    },
    isPremium: false,
    displayComments: false,
    headline: 'Amplify grants launched to grow local businesses',
    displayDate: '2022-11-22T11:00:00Z',
    publishDate: '2022-11-22T11:00:00Z',
    isUpdated: false,
    description: 'Good businesses become great when their potential is amplified with the right support at',
    readTime: '3 minutes to read',
    websiteUrl: '/whanganui-chronicle/sponsored-stories/amplify-grants-launched-to-grow-local-businesses/CCU5I6FKOTN52JCV3KZHNJQQNY/',
    linkTarget: '_self',
    source: {
      edit_url: 'https://dev-zen.devlbcf.apnnz.co.nz/v2/index.cfm?page=article&objectid=12577332',
      name: '',
      source_id: '12577332',
      source_type: 'wires',
      system: 'Zen'
    },
    sections: [ [Object] ],
    website: 'whanganui-chronicle',
    tags: [ [Object] ],
    authors: [ [Object] ],
    hasArticlePromoVideo: false,
    nzhVideo: {},
    accentColor: 'section-sponsored-stories',
    sectionLabel: 'Sponsored Stories',
    sectionLabelLink: '/whanganui-chronicle/sponsored-stories/',
    subSectionLabel: '',
    subSectionLabelLink: '',
    isSponsored: true,
    subtype: 'commercial-articles'
  }
]

export const initTopics = [
  { id: 1, name: 'NZH Top 5',       href: 'christmas', icon: HomeIcon },
  { id: 2, name: 'Business',        href: 'business-hub',  icon: BriefcaseIcon },
  { id: 3, name: 'Entertainment',   href: 'bopt-entertainment',  icon: UsersIcon },
  { id: 4, name: 'Rugby',           href: 'rugby',  icon: TrophyIcon },
  { id: 5, name: 'Politics',        href: 'best-of-political-analysis',  icon: ChatBubbleBottomCenterIcon },
  { id: 6, name: 'World',           href: 'birkenhead',  icon: GlobeEuropeAfricaIcon },
  { id: 7, name: 'Sport',           href: 'college-sport',  icon: GlobeAltIcon },
  { id: 8, name: 'Opinion',         href: 'akl-opinion',  icon: CursorArrowRaysIcon },
  { id: 9, name: 'Property',        href: 'commercial-property',  icon: HomeModernIcon },
  { id: 10, name: 'Crime',          href: 'a-moment-in-crime',  icon: BellIcon },
]
